//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.GoodReads {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.GoodReads.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Now.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog post.
        /// </summary>
        public static string BlogPostType {
            get {
                return ResourceManager.GetString("BlogPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string BookPostType {
            get {
                return ResourceManager.GetString("BookPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Discover&lt;/b&gt; content by Tags, Type, Suggested by and sort by Popularity/latest based on your interest. &lt;br /&gt;
        ///&lt;b&gt;Add content&lt;/b&gt; to your private list and visit later to learn and grow.
        /// &lt;br /&gt;
        ///&lt;b&gt;Share&lt;/b&gt; content that influenced or inspired you with your co-workers..
        /// </summary>
        public static string CarouselCard1Text {
            get {
                return ResourceManager.GetString("CarouselCard1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a &lt;b&gt;digest of content&lt;/b&gt; that are added based on your preference in a channel to stay updated on the topics..
        /// </summary>
        public static string CarouselCard2Text {
            get {
                return ResourceManager.GetString("CarouselCard2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Add&lt;/b&gt; {0} to the Channel Tab based on tags to learn together with your team.
        ///&lt;br /&gt;
        ///&lt;b&gt;Share&lt;/b&gt; your favorite reads in a channel or chat to help your Peers grow..
        /// </summary>
        public static string CarouselCard3Text {
            get {
                return ResourceManager.GetString("CarouselCard3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set digest preference by selecting the frequency and tab you wants to follow..
        /// </summary>
        public static string DigestPreferenceCardContent {
            get {
                return ResourceManager.GetString("DigestPreferenceCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can configure more topics or different ones as well as change how often the digest is posted..
        /// </summary>
        public static string DigestPreferenceCardHeaderText {
            get {
                return ResourceManager.GetString("DigestPreferenceCardHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monthly digest.
        /// </summary>
        public static string NotificationCardMonthlyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardMonthlyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly digest.
        /// </summary>
        public static string NotificationCardWeeklyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardWeeklyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string NotificationListCardViewMoreButtonText {
            get {
                return ResourceManager.GetString("NotificationListCardViewMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open item.
        /// </summary>
        public static string OpenItem {
            get {
                return ResourceManager.GetString("OpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherPostType {
            get {
                return ResourceManager.GetString("OtherPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string PersonalWelcomeCardDiscoverButtonText {
            get {
                return ResourceManager.GetString("PersonalWelcomeCardDiscoverButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podcast.
        /// </summary>
        public static string PodcastPostType {
            get {
                return ResourceManager.GetString("PodcastPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabelText {
            get {
                return ResourceManager.GetString("TagsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string TeamPreferenceCardConfigureButtonText {
            get {
                return ResourceManager.GetString("TeamPreferenceCardConfigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string TeamWelcomeCardConfigureButtonText {
            get {
                return ResourceManager.GetString("TeamWelcomeCardConfigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoPostType {
            get {
                return ResourceManager.GetString("VideoPostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string VoteImageAltText {
            get {
                return ResourceManager.GetString("VoteImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the commands I follow and what they do:.
        /// </summary>
        public static string WelcomeCardCommandHeaderText {
            get {
                return ResourceManager.GetString("WelcomeCardCommandHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here to help your team discover and share great articles, videos, and other types of content..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Save:** Create a private list of links to visit later.
        /// </summary>
        public static string WelcomeCardCreatePrivateList {
            get {
                return ResourceManager.GetString("WelcomeCardCreatePrivateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Discover:** Get content suggestions from colleagues.
        /// </summary>
        public static string WelcomeCardDiscoverText {
            get {
                return ResourceManager.GetString("WelcomeCardDiscoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Suggest:** Share content that&apos;s relevant to your team.
        /// </summary>
        public static string WelcomeCardSuggestText {
            get {
                return ResourceManager.GetString("WelcomeCardSuggestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a **digest of content** that are added based on your preference in a channel to stay updated on the topics..
        /// </summary>
        public static string WelcomeCardTeamDigestContent {
            get {
                return ResourceManager.GetString("WelcomeCardTeamDigestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Search &amp; Share** your favorite reads in a channel or chat to help your Peers grow..
        /// </summary>
        public static string WelcomeCardTeamShareContent {
            get {
                return ResourceManager.GetString("WelcomeCardTeamShareContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
